before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0]
    goarch: [amd64, arm64]
    goos: [linux]

archives:
  - format: zip
    wrap_in_directory: extensions
    files: [none*]

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc

release:
  github:
    owner: cludden
    name: gomplate-lambda-extension
